ALTER TABLE candidatos
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE candidaturas
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE contratos
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE dados_bancarios
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE departamentos
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE folhas_de_pagamento
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE funcionarios
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE usuarios
ADD COLUMN version INT NOT NULL DEFAULT 1;

ALTER TABLE vagas
ADD COLUMN version INT NOT NULL DEFAULT 1;